captainVersion: 4
services:
  $$cap_appname-db:
    image: postgres:$$cap_db_version
    volumes:
      - $$cap_appname-db-data:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: $$cap_db_user
      POSTGRES_PASSWORD: $$cap_db_password
      POSTGRES_DB: $$cap_db_name
    caproverExtra:
      notExposeAsWebApp: true
caproverOneClickApp:
    variables:
      - id: $$cap_db_version
        label: Database Version
        description: The version of the database to use
        defaultValue: 15
        validRegex: "^(9|10|11|12|13|14|15)$"
      - id: $$cap_db_user
        label: Database User
        description: The user to use for the database
        defaultValue: hoppscotch
        validRegex: "^[a-zA-Z0-9_]+$"
      - id: $$cap_db_password
        label: Database Password
        description: The password to use for the database
        defaultValue: hoppscotch
        validRegex: "^[a-zA-Z0-9_]+$"
      - id: $$cap_db_name
        label: Database Name
        description: The name of the database to use
        defaultValue: hoppscotch
        validRegex: "^[a-zA-Z0-9_]+$"
    instructions:
      start: >-
        Hoppscotch is an open-source API development ecosystem. It helps you create, share, maintain, and visualize APIs. This one-click app will deploy Hoppscotch with a PostgreSQL database.
      end: >-
        Hoppscotch is now deployed with a PostgreSQL database. You can access it by clicking on the "Open App" button.
    displayName: Hoppscotch
    isOfficial: true
    description: An open-source API development ecosystem
    documentation: https://hoppscotch.io